<a href="https://colab.research.google.com/github/suzume2006/HTML-codes/blob/main/python-notebook/numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

import numpy as np
a=np.array(34)
a.ndim

0

In [2]:

import numpy as np
v=np.array([[]])
v.ndim

2

In [3]:
b=np.array([[[[]]]])
b.ndim
b.shape

(1, 1, 1, 0)

In [4]:
arr=np.arange(0,10)
arr
ar=np.arange(0,11,3)
ar

array([0, 3, 6, 9])

In [7]:

arr=np.linspace(2,3,7)
arr

array([2.        , 2.16666667, 2.33333333, 2.5       , 2.66666667,
       2.83333333, 3.        ])

In [6]:
arr=np.logspace(3,4,5)
arr

array([ 1000.        ,  1778.27941004,  3162.27766017,  5623.4132519 ,
       10000.        ])

In [5]:
arr=np.zeros([4,3])
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
data=np.full((2,4),9)
data

array([[9, 9, 9, 9],
       [9, 9, 9, 9]])

In [16]:

arr=np.random.rand(4,5)
arr

array([[0.96633719, 0.40080927, 0.78410286, 0.3508773 , 0.46402377],
       [0.95466123, 0.37222384, 0.38996757, 0.4654341 , 0.62050513],
       [0.38646199, 0.09464077, 0.29081134, 0.98005714, 0.73740075],
       [0.42287149, 0.12856049, 0.1819676 , 0.34780798, 0.97757001]])

In [14]:
arr=np.array([1,33,45,67,89],dtype=np.float128)
arr

array([ 1., 33., 45., 67., 89.], dtype=float128)

In [13]:

arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [12]:

new_arr=arr.astype(np.float64)
new_arr


array([[ 2.,  3.,  4.,  5.],
       [ 2.,  5.,  9., 80.]])

In [17]:
new_arr2=new_arr.astype(np.int16)
new_arr2


array([[ 2,  3,  4,  5],
       [ 2,  5,  9, 80]], dtype=int16)

In [10]:
arr=np.array([[2,3,4,5],[2,5,9,80]])
arr
arr.ndim
arr.shape

(2, 4)

In [18]:

arr=np.array([1,2,3,4,5,6,7,8])
reshapes=arr.reshape(2,4)
print(reshapes)

[[1 2 3 4]
 [5 6 7 8]]


In [19]:

reshape1=reshapes.reshape(2,2,2)
print(reshape1)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [39]:
ravel=reshape1.ravel()
print(ravel)

[1 2 3 4 5 6 7 8]


In [40]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,11])
print(a+b)

[ 7  9 11 13 16]


In [41]:
print(a-b)

[-5 -5 -5 -5 -6]


In [42]:

print(a*b)

[ 6 14 24 36 55]


In [43]:

print(b/a)

[6.         3.5        2.66666667 2.25       2.2       ]


In [44]:

print(a**b)

[       1      128     6561   262144 48828125]


In [45]:

print(np.exp([2,3]))


[ 7.3890561  20.08553692]


In [22]:
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix[1: ,1:])

[[5 6]
 [8 9]]


In [35]:
arr=np.array([1,2,3,4,5,6])
view=arr[1:4]


In [36]:
print(arr)

[1 2 3 4 5 6]


In [37]:

copy=arr[1:4].copy()
copy

array([2, 3, 4])

In [38]:

copy[2]=300
copy

array([  2,   3, 300])

In [34]:
print(arr)


[1 2 3 4]


In [33]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
combine=np.concatenate((a,b))
combine

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
a=np.array([[1,2],[4,6]])
b=np.array([[7,8],[9,10]])
print(np.vstack((a,b)))

[[ 1  2]
 [ 4  6]
 [ 7  8]
 [ 9 10]]


In [46]:
print(np.hstack((a,b)))

[ 1  2  3  4  5  6  7  8  9 11]


In [28]:
arr=np.array([1,2,3,4,])
print(np.repeat(arr,2))

[1 1 2 2 3 3 4 4]


In [27]:
print(np.tile(arr,4))

[1 2 3 1 2 3 1 2 3 1 2 3]


In [26]:
matrix=np.array([[[1,2,3,],[2,5,6],[7,8,4]]])
print(matrix)

[[[1 2 3]
  [2 5 6]
  [7 8 4]]]


In [29]:
print(np.sum(matrix,axis=0))

[[1 2 3]
 [2 5 6]
 [7 8 4]]


In [25]:
print(np.sum(matrix,axis=1))

[ 6 15 24]


In [24]:
arr=np.array([1,2,3])
print(np.cumsum(arr))

[1 3 6]


In [23]:

arr=np.array([10,20,30,40])
print(np.argwhere(arr>20))

[[2]
 [3]]
